import glob
import os
import shutil
from utils import files_in_dir, initialize_recursive_dataset
from utils_ML import classify_image_type

def filter_dataset_by_imagetype(dataset_dir_in="datasets_base",dataset_dir_out="datasets_anime",rejected_dir_top="Images/rejected_images"):
    '''
    INPUTS
    All variables point to the top level directory, with images stored in their repsective class folders.
    dataset_dir_in - initial dataset, in this case generated by downloading images from google images, which isn't very precise
    dataset_dir_out - dataset for accepted images that are determined to match the artstyle of the anime we want
    rejected_dir_top - dataset to store images that are filtered out
    '''
    dirs = glob.glob(os.path.join(dataset_dir_in,'*'))
    model = None
    for dir in dirs:
        images_list = files_in_dir(dir)
        accepted_dir = os.path.join(dataset_dir_out,os.path.basename(dir))
        os.makedirs(accepted_dir,exist_ok=True)
        rejected_dir = os.path.join(rejected_dir_top,os.path.basename(dir))
        os.makedirs(rejected_dir,exist_ok=True)
        for file in images_list:
            predicted_class_label, model = classify_image_type(file,model=model)
            if predicted_class_label == "this_anime":
                shutil.copy(file,os.path.join(accepted_dir,os.path.basename(file)))
            else:
                name, ext = os.path.splitext(os.path.basename(file))
                out_name = os.path.join(rejected_dir,name+'-'+predicted_class_label+ext)
                shutil.copy(file,out_name)

if __name__ == "__main__":
    # filter_dataset_by_imagetype("datasets_base")
    initialize_recursive_dataset()
